// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'DSA',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'DSA'}],
    },
    {
      type: 'category',
      label: 'System Design',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'System Design'}],
    },
    {
      type: 'category',
      label: 'Development',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'Development'},
      ],
    },
    {
      type: 'category',
      label: 'AIML',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'AIML'}],
    },
    {
      type: 'category',
      label: 'Core Subjects',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'Core Subjects'}],
    },
  ],
};

export default sidebars;
